[build]
  command = "npm install --legacy-peer-deps --include=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --include=optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
